server:
  port: 8080

spring:
  application:
    name: sifpi

  profiles:
    active:
      - dev

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, caches
  endpoint:
    health:
      show-details: when-authorized

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000
  cookie-name: SIFPI_TOKEN
  cookie-path: /
  cookie-secure: true
  cookie-same-site: Lax
